# Generated by Django 5.0.2 on 2024-03-13 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helloweb', '0002_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.URLField(default='http://placehold.it/900x300'),
        ),
    ]
