# Generated by Django 5.0.2 on 2024-03-13 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helloweb', '0003_post_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'Тег',
                'verbose_name_plural': 'Теги',
            },
        ),
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(to='helloweb.tag'),
        ),
    ]
