# Generated by Django 5.0.2 on 2024-03-20 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helloweb', '0004_tag_post_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsersEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Користувачі для розсилки',
                'verbose_name_plural': 'Користувачі для розсилки',
            },
        ),
    ]
