# Generated by Django 5.0.2 on 2024-03-20 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helloweb', '0005_usersemail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usersemail',
            old_name='email',
            new_name='user_email',
        ),
    ]
